name: Build and push Python 3.8 image (GHCR)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'python/3.8/**'
      - '.github/workflows/build-and-push-ghcr-3.8.yml'

permissions:
  contents: read
  packages: write
  id-token: write

env:
  GHCR_IMAGE: ghcr.io/runningbird/docker-img/python

jobs:
  build-and-push-ghcr-3-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR (amd64)
        uses: docker/build-push-action@v4
        with:
          context: ./python/3.8
          file: ./python/3.8/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:3.8
            ${{ env.GHCR_IMAGE }}:python-3.8
